
strategy_name: stg_test
log_path: ./logs
interval: 1

gateway:
  BINANCEUBC:
    key: Sr6gmFe7r3CWJYCgY7Zm67bVDZ1ODj9xotjT98ZbkqMPiTfvP4H4RuzAOFPG4wTw
    secret: uiVMJ6GePcqrq18MCTqamlBZnmvlEkzgIJ3zxMBWXpYztWFbtgjGGfKGoqwjstdD
    test_net: REAL #REAL or TESTNET
    proxy_host: localhost
    proxy_port: 1087
    minute_limit: 1000
    second_limit: 200
#  BINANCEBBC:
#    key: Sr6gmFe7r3CWJYCgY7Zm67bVDZ1ODj9xotjT98ZbkqMPiTfvP4H4RuzAOFPG4wTw1
#    secret: uiVMJ6GePcqrq18MCTqamlBZnmvlEkzgIJ3zxMBWXpYztWFbtgjGGfKGoqwjstdD1
#    test_net: REAL #REAL or TESTNET
#    proxy_host: localhost
#    proxy_port: 1087
#    symbol: ''
  BITMEX:
    key: _HQWiAWT-1IpDRZ1oWHUSIoF
    secret: MCIMG89cCUEtckuKSM7s09oUAV1lq13fdqcbBdk621ALvYbE
    test_net: TESTNET #REAL or TESTNET
    proxy_host: localhost
    proxy_port: 1087
    minute_limit: 60
    second_limit: 60
