---
version: 1
disable_existing_loggers: False
formatters:
    default:
        format: "[%(asctime)s][%(threadName)s][%(levelname)s][%(name)s][%(funcName)s] - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: default
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: default
        filename: logs/stdout.log
        when: d
        interval: 1
        backupCount: 30
        encoding: utf8

loggers:
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console, file_handler]